/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MinStay implements org.apache.thrift.TBase<MinStay, MinStay._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MinStay");

  private static final org.apache.thrift.protocol.TField MIN_STAY_ITEM_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("minStayItemList", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField ACROSS_WEEKEND_FIELD_DESC = new org.apache.thrift.protocol.TField("acrossWeekend", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MinStayStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MinStayTupleSchemeFactory());
  }

  public List<com.travelzen.farerule.rule.MinStayItem> minStayItemList; // optional
  public boolean acrossWeekend; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MIN_STAY_ITEM_LIST((short)1, "minStayItemList"),
    ACROSS_WEEKEND((short)2, "acrossWeekend");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MIN_STAY_ITEM_LIST
          return MIN_STAY_ITEM_LIST;
        case 2: // ACROSS_WEEKEND
          return ACROSS_WEEKEND;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACROSSWEEKEND_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.MIN_STAY_ITEM_LIST,_Fields.ACROSS_WEEKEND};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MIN_STAY_ITEM_LIST, new org.apache.thrift.meta_data.FieldMetaData("minStayItemList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.travelzen.farerule.rule.MinStayItem.class))));
    tmpMap.put(_Fields.ACROSS_WEEKEND, new org.apache.thrift.meta_data.FieldMetaData("acrossWeekend", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MinStay.class, metaDataMap);
  }

  public MinStay() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MinStay(MinStay other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMinStayItemList()) {
      List<com.travelzen.farerule.rule.MinStayItem> __this__minStayItemList = new ArrayList<com.travelzen.farerule.rule.MinStayItem>();
      for (com.travelzen.farerule.rule.MinStayItem other_element : other.minStayItemList) {
        __this__minStayItemList.add(new com.travelzen.farerule.rule.MinStayItem(other_element));
      }
      this.minStayItemList = __this__minStayItemList;
    }
    this.acrossWeekend = other.acrossWeekend;
  }

  public MinStay deepCopy() {
    return new MinStay(this);
  }

  @Override
  public void clear() {
    this.minStayItemList = null;
    setAcrossWeekendIsSet(false);
    this.acrossWeekend = false;
  }

  public int getMinStayItemListSize() {
    return (this.minStayItemList == null) ? 0 : this.minStayItemList.size();
  }

  public java.util.Iterator<com.travelzen.farerule.rule.MinStayItem> getMinStayItemListIterator() {
    return (this.minStayItemList == null) ? null : this.minStayItemList.iterator();
  }

  public void addToMinStayItemList(com.travelzen.farerule.rule.MinStayItem elem) {
    if (this.minStayItemList == null) {
      this.minStayItemList = new ArrayList<com.travelzen.farerule.rule.MinStayItem>();
    }
    this.minStayItemList.add(elem);
  }

  public List<com.travelzen.farerule.rule.MinStayItem> getMinStayItemList() {
    return this.minStayItemList;
  }

  public MinStay setMinStayItemList(List<com.travelzen.farerule.rule.MinStayItem> minStayItemList) {
    this.minStayItemList = minStayItemList;
    return this;
  }

  public void unsetMinStayItemList() {
    this.minStayItemList = null;
  }

  /** Returns true if field minStayItemList is set (has been assigned a value) and false otherwise */
  public boolean isSetMinStayItemList() {
    return this.minStayItemList != null;
  }

  public void setMinStayItemListIsSet(boolean value) {
    if (!value) {
      this.minStayItemList = null;
    }
  }

  public boolean isAcrossWeekend() {
    return this.acrossWeekend;
  }

  public MinStay setAcrossWeekend(boolean acrossWeekend) {
    this.acrossWeekend = acrossWeekend;
    setAcrossWeekendIsSet(true);
    return this;
  }

  public void unsetAcrossWeekend() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ACROSSWEEKEND_ISSET_ID);
  }

  /** Returns true if field acrossWeekend is set (has been assigned a value) and false otherwise */
  public boolean isSetAcrossWeekend() {
    return EncodingUtils.testBit(__isset_bitfield, __ACROSSWEEKEND_ISSET_ID);
  }

  public void setAcrossWeekendIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ACROSSWEEKEND_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MIN_STAY_ITEM_LIST:
      if (value == null) {
        unsetMinStayItemList();
      } else {
        setMinStayItemList((List<com.travelzen.farerule.rule.MinStayItem>)value);
      }
      break;

    case ACROSS_WEEKEND:
      if (value == null) {
        unsetAcrossWeekend();
      } else {
        setAcrossWeekend((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MIN_STAY_ITEM_LIST:
      return getMinStayItemList();

    case ACROSS_WEEKEND:
      return Boolean.valueOf(isAcrossWeekend());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MIN_STAY_ITEM_LIST:
      return isSetMinStayItemList();
    case ACROSS_WEEKEND:
      return isSetAcrossWeekend();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MinStay)
      return this.equals((MinStay)that);
    return false;
  }

  public boolean equals(MinStay that) {
    if (that == null)
      return false;

    boolean this_present_minStayItemList = true && this.isSetMinStayItemList();
    boolean that_present_minStayItemList = true && that.isSetMinStayItemList();
    if (this_present_minStayItemList || that_present_minStayItemList) {
      if (!(this_present_minStayItemList && that_present_minStayItemList))
        return false;
      if (!this.minStayItemList.equals(that.minStayItemList))
        return false;
    }

    boolean this_present_acrossWeekend = true && this.isSetAcrossWeekend();
    boolean that_present_acrossWeekend = true && that.isSetAcrossWeekend();
    if (this_present_acrossWeekend || that_present_acrossWeekend) {
      if (!(this_present_acrossWeekend && that_present_acrossWeekend))
        return false;
      if (this.acrossWeekend != that.acrossWeekend)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(MinStay other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MinStay typedOther = (MinStay)other;

    lastComparison = Boolean.valueOf(isSetMinStayItemList()).compareTo(typedOther.isSetMinStayItemList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinStayItemList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.minStayItemList, typedOther.minStayItemList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAcrossWeekend()).compareTo(typedOther.isSetAcrossWeekend());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAcrossWeekend()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.acrossWeekend, typedOther.acrossWeekend);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MinStay(");
    boolean first = true;

    if (isSetMinStayItemList()) {
      sb.append("minStayItemList:");
      if (this.minStayItemList == null) {
        sb.append("null");
      } else {
        sb.append(this.minStayItemList);
      }
      first = false;
    }
    if (isSetAcrossWeekend()) {
      if (!first) sb.append(", ");
      sb.append("acrossWeekend:");
      sb.append(this.acrossWeekend);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MinStayStandardSchemeFactory implements SchemeFactory {
    public MinStayStandardScheme getScheme() {
      return new MinStayStandardScheme();
    }
  }

  private static class MinStayStandardScheme extends StandardScheme<MinStay> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MinStay struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MIN_STAY_ITEM_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list32 = iprot.readListBegin();
                struct.minStayItemList = new ArrayList<com.travelzen.farerule.rule.MinStayItem>(_list32.size);
                for (int _i33 = 0; _i33 < _list32.size; ++_i33)
                {
                  com.travelzen.farerule.rule.MinStayItem _elem34; // required
                  _elem34 = new com.travelzen.farerule.rule.MinStayItem();
                  _elem34.read(iprot);
                  struct.minStayItemList.add(_elem34);
                }
                iprot.readListEnd();
              }
              struct.setMinStayItemListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ACROSS_WEEKEND
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.acrossWeekend = iprot.readBool();
              struct.setAcrossWeekendIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MinStay struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.minStayItemList != null) {
        if (struct.isSetMinStayItemList()) {
          oprot.writeFieldBegin(MIN_STAY_ITEM_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.minStayItemList.size()));
            for (com.travelzen.farerule.rule.MinStayItem _iter35 : struct.minStayItemList)
            {
              _iter35.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetAcrossWeekend()) {
        oprot.writeFieldBegin(ACROSS_WEEKEND_FIELD_DESC);
        oprot.writeBool(struct.acrossWeekend);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MinStayTupleSchemeFactory implements SchemeFactory {
    public MinStayTupleScheme getScheme() {
      return new MinStayTupleScheme();
    }
  }

  private static class MinStayTupleScheme extends TupleScheme<MinStay> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MinStay struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMinStayItemList()) {
        optionals.set(0);
      }
      if (struct.isSetAcrossWeekend()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMinStayItemList()) {
        {
          oprot.writeI32(struct.minStayItemList.size());
          for (com.travelzen.farerule.rule.MinStayItem _iter36 : struct.minStayItemList)
          {
            _iter36.write(oprot);
          }
        }
      }
      if (struct.isSetAcrossWeekend()) {
        oprot.writeBool(struct.acrossWeekend);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MinStay struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list37 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.minStayItemList = new ArrayList<com.travelzen.farerule.rule.MinStayItem>(_list37.size);
          for (int _i38 = 0; _i38 < _list37.size; ++_i38)
          {
            com.travelzen.farerule.rule.MinStayItem _elem39; // required
            _elem39 = new com.travelzen.farerule.rule.MinStayItem();
            _elem39.read(iprot);
            struct.minStayItemList.add(_elem39);
          }
        }
        struct.setMinStayItemListIsSet(true);
      }
      if (incoming.get(1)) {
        struct.acrossWeekend = iprot.readBool();
        struct.setAcrossWeekendIsSet(true);
      }
    }
  }

}

