/* Generated By:JavaCC: Do not edit this line. DetrParserConstants.java */
package com.travelzen.etermface.service.abe_imitator.ticket.detr;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DetrParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letter = 2;
  /** RegularExpression Id. */
  int number = 3;
  /** RegularExpression Id. */
  int city = 4;
  /** RegularExpression Id. */
  int flightNoOrtime = 5;
  /** RegularExpression Id. */
  int date = 6;
  /** RegularExpression Id. */
  int allow = 7;
  /** RegularExpression Id. */
  int at = 8;
  /** RegularExpression Id. */
  int dFltStatusMsgOrword = 9;
  /** RegularExpression Id. */
  int lFltStatusMsgOrword = 10;
  /** RegularExpression Id. */
  int carrierOrStatusOrAt = 11;
  /** RegularExpression Id. */
  int fltStatusMsg = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "<letter>",
    "<number>",
    "<city>",
    "<flightNoOrtime>",
    "<date>",
    "<allow>",
    "\"--\"",
    "<dFltStatusMsgOrword>",
    "<lFltStatusMsgOrword>",
    "<carrierOrStatusOrAt>",
    "<fltStatusMsg>",
    "\" \"",
    "\"FM:\"",
    "\"TO:\"",
    "\"VOID \"",
    "\"OPEN \"",
    "\"/\"",
    "\"RL:\"",
  };

}
