/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule.condition;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OriginTypeEnum implements org.apache.thrift.TEnum {
  ORIGIN(0),
  OUTBOUND(1),
  INBOUND(2),
  ALL(3);

  private final int value;

  private OriginTypeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OriginTypeEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return ORIGIN;
      case 1:
        return OUTBOUND;
      case 2:
        return INBOUND;
      case 3:
        return ALL;
      default:
        return null;
    }
  }
}
