/* Generated By:JavaCC: Do not edit this line. PublicFareSearchParserConstants.java */
package com.travelzen.javacc.publics;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PublicFareSearchParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int rowNum = 7;
  /** RegularExpression Id. */
  int city = 8;
  /** RegularExpression Id. */
  int date = 9;
  /** RegularExpression Id. */
  int journey = 10;
  /** RegularExpression Id. */
  int money = 11;
  /** RegularExpression Id. */
  int moneyRt = 12;
  /** RegularExpression Id. */
  int distance = 13;
  /** RegularExpression Id. */
  int priceId = 14;
  /** RegularExpression Id. */
  int priceBase = 15;
  /** RegularExpression Id. */
  int rowEnd = 16;
  /** RegularExpression Id. */
  int pageEnd = 17;
  /** RegularExpression Id. */
  int bookClass = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\".\"",
    "\"/CNY\"",
    "\"/\"",
    "<rowNum>",
    "<city>",
    "<date>",
    "<journey>",
    "<money>",
    "<moneyRt>",
    "<distance>",
    "<priceId>",
    "<priceBase>",
    "<rowEnd>",
    "<pageEnd>",
    "<bookClass>",
    "\"(PFD\"",
    "\"FD:\"",
    "\"=\"",
  };

}
