/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TravelDate implements org.apache.thrift.TBase<TravelDate, TravelDate._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TravelDate");

  private static final org.apache.thrift.protocol.TField TRAVEL_DATE_ITEM_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("travelDateItemList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TravelDateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TravelDateTupleSchemeFactory());
  }

  public List<com.travelzen.farerule.rule.TravelDateItem> travelDateItemList; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRAVEL_DATE_ITEM_LIST((short)1, "travelDateItemList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRAVEL_DATE_ITEM_LIST
          return TRAVEL_DATE_ITEM_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.TRAVEL_DATE_ITEM_LIST};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRAVEL_DATE_ITEM_LIST, new org.apache.thrift.meta_data.FieldMetaData("travelDateItemList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.travelzen.farerule.rule.TravelDateItem.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TravelDate.class, metaDataMap);
  }

  public TravelDate() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TravelDate(TravelDate other) {
    if (other.isSetTravelDateItemList()) {
      List<com.travelzen.farerule.rule.TravelDateItem> __this__travelDateItemList = new ArrayList<com.travelzen.farerule.rule.TravelDateItem>();
      for (com.travelzen.farerule.rule.TravelDateItem other_element : other.travelDateItemList) {
        __this__travelDateItemList.add(new com.travelzen.farerule.rule.TravelDateItem(other_element));
      }
      this.travelDateItemList = __this__travelDateItemList;
    }
  }

  public TravelDate deepCopy() {
    return new TravelDate(this);
  }

  @Override
  public void clear() {
    this.travelDateItemList = null;
  }

  public int getTravelDateItemListSize() {
    return (this.travelDateItemList == null) ? 0 : this.travelDateItemList.size();
  }

  public java.util.Iterator<com.travelzen.farerule.rule.TravelDateItem> getTravelDateItemListIterator() {
    return (this.travelDateItemList == null) ? null : this.travelDateItemList.iterator();
  }

  public void addToTravelDateItemList(com.travelzen.farerule.rule.TravelDateItem elem) {
    if (this.travelDateItemList == null) {
      this.travelDateItemList = new ArrayList<com.travelzen.farerule.rule.TravelDateItem>();
    }
    this.travelDateItemList.add(elem);
  }

  public List<com.travelzen.farerule.rule.TravelDateItem> getTravelDateItemList() {
    return this.travelDateItemList;
  }

  public TravelDate setTravelDateItemList(List<com.travelzen.farerule.rule.TravelDateItem> travelDateItemList) {
    this.travelDateItemList = travelDateItemList;
    return this;
  }

  public void unsetTravelDateItemList() {
    this.travelDateItemList = null;
  }

  /** Returns true if field travelDateItemList is set (has been assigned a value) and false otherwise */
  public boolean isSetTravelDateItemList() {
    return this.travelDateItemList != null;
  }

  public void setTravelDateItemListIsSet(boolean value) {
    if (!value) {
      this.travelDateItemList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TRAVEL_DATE_ITEM_LIST:
      if (value == null) {
        unsetTravelDateItemList();
      } else {
        setTravelDateItemList((List<com.travelzen.farerule.rule.TravelDateItem>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TRAVEL_DATE_ITEM_LIST:
      return getTravelDateItemList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TRAVEL_DATE_ITEM_LIST:
      return isSetTravelDateItemList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TravelDate)
      return this.equals((TravelDate)that);
    return false;
  }

  public boolean equals(TravelDate that) {
    if (that == null)
      return false;

    boolean this_present_travelDateItemList = true && this.isSetTravelDateItemList();
    boolean that_present_travelDateItemList = true && that.isSetTravelDateItemList();
    if (this_present_travelDateItemList || that_present_travelDateItemList) {
      if (!(this_present_travelDateItemList && that_present_travelDateItemList))
        return false;
      if (!this.travelDateItemList.equals(that.travelDateItemList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TravelDate other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TravelDate typedOther = (TravelDate)other;

    lastComparison = Boolean.valueOf(isSetTravelDateItemList()).compareTo(typedOther.isSetTravelDateItemList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTravelDateItemList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.travelDateItemList, typedOther.travelDateItemList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TravelDate(");
    boolean first = true;

    if (isSetTravelDateItemList()) {
      sb.append("travelDateItemList:");
      if (this.travelDateItemList == null) {
        sb.append("null");
      } else {
        sb.append(this.travelDateItemList);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TravelDateStandardSchemeFactory implements SchemeFactory {
    public TravelDateStandardScheme getScheme() {
      return new TravelDateStandardScheme();
    }
  }

  private static class TravelDateStandardScheme extends StandardScheme<TravelDate> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TravelDate struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRAVEL_DATE_ITEM_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list48 = iprot.readListBegin();
                struct.travelDateItemList = new ArrayList<com.travelzen.farerule.rule.TravelDateItem>(_list48.size);
                for (int _i49 = 0; _i49 < _list48.size; ++_i49)
                {
                  com.travelzen.farerule.rule.TravelDateItem _elem50; // required
                  _elem50 = new com.travelzen.farerule.rule.TravelDateItem();
                  _elem50.read(iprot);
                  struct.travelDateItemList.add(_elem50);
                }
                iprot.readListEnd();
              }
              struct.setTravelDateItemListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TravelDate struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.travelDateItemList != null) {
        if (struct.isSetTravelDateItemList()) {
          oprot.writeFieldBegin(TRAVEL_DATE_ITEM_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.travelDateItemList.size()));
            for (com.travelzen.farerule.rule.TravelDateItem _iter51 : struct.travelDateItemList)
            {
              _iter51.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TravelDateTupleSchemeFactory implements SchemeFactory {
    public TravelDateTupleScheme getScheme() {
      return new TravelDateTupleScheme();
    }
  }

  private static class TravelDateTupleScheme extends TupleScheme<TravelDate> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TravelDate struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTravelDateItemList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTravelDateItemList()) {
        {
          oprot.writeI32(struct.travelDateItemList.size());
          for (com.travelzen.farerule.rule.TravelDateItem _iter52 : struct.travelDateItemList)
          {
            _iter52.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TravelDate struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list53 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.travelDateItemList = new ArrayList<com.travelzen.farerule.rule.TravelDateItem>(_list53.size);
          for (int _i54 = 0; _i54 < _list53.size; ++_i54)
          {
            com.travelzen.farerule.rule.TravelDateItem _elem55; // required
            _elem55 = new com.travelzen.farerule.rule.TravelDateItem();
            _elem55.read(iprot);
            struct.travelDateItemList.add(_elem55);
          }
        }
        struct.setTravelDateItemListIsSet(true);
      }
    }
  }

}

