/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule.rule;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DayTimeSubItem implements org.apache.thrift.TBase<DayTimeSubItem, DayTimeSubItem._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DayTimeSubItem");

  private static final org.apache.thrift.protocol.TField START_TIME_POINT_FIELD_DESC = new org.apache.thrift.protocol.TField("startTimePoint", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField END_TIME_POINT_FIELD_DESC = new org.apache.thrift.protocol.TField("endTimePoint", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DayTimeSubItemStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DayTimeSubItemTupleSchemeFactory());
  }

  public DayTimePoint startTimePoint; // optional
  public DayTimePoint endTimePoint; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    START_TIME_POINT((short)1, "startTimePoint"),
    END_TIME_POINT((short)2, "endTimePoint");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // START_TIME_POINT
          return START_TIME_POINT;
        case 2: // END_TIME_POINT
          return END_TIME_POINT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.START_TIME_POINT,_Fields.END_TIME_POINT};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.START_TIME_POINT, new org.apache.thrift.meta_data.FieldMetaData("startTimePoint", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DayTimePoint.class)));
    tmpMap.put(_Fields.END_TIME_POINT, new org.apache.thrift.meta_data.FieldMetaData("endTimePoint", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DayTimePoint.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DayTimeSubItem.class, metaDataMap);
  }

  public DayTimeSubItem() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DayTimeSubItem(DayTimeSubItem other) {
    if (other.isSetStartTimePoint()) {
      this.startTimePoint = new DayTimePoint(other.startTimePoint);
    }
    if (other.isSetEndTimePoint()) {
      this.endTimePoint = new DayTimePoint(other.endTimePoint);
    }
  }

  public DayTimeSubItem deepCopy() {
    return new DayTimeSubItem(this);
  }

  @Override
  public void clear() {
    this.startTimePoint = null;
    this.endTimePoint = null;
  }

  public DayTimePoint getStartTimePoint() {
    return this.startTimePoint;
  }

  public DayTimeSubItem setStartTimePoint(DayTimePoint startTimePoint) {
    this.startTimePoint = startTimePoint;
    return this;
  }

  public void unsetStartTimePoint() {
    this.startTimePoint = null;
  }

  /** Returns true if field startTimePoint is set (has been assigned a value) and false otherwise */
  public boolean isSetStartTimePoint() {
    return this.startTimePoint != null;
  }

  public void setStartTimePointIsSet(boolean value) {
    if (!value) {
      this.startTimePoint = null;
    }
  }

  public DayTimePoint getEndTimePoint() {
    return this.endTimePoint;
  }

  public DayTimeSubItem setEndTimePoint(DayTimePoint endTimePoint) {
    this.endTimePoint = endTimePoint;
    return this;
  }

  public void unsetEndTimePoint() {
    this.endTimePoint = null;
  }

  /** Returns true if field endTimePoint is set (has been assigned a value) and false otherwise */
  public boolean isSetEndTimePoint() {
    return this.endTimePoint != null;
  }

  public void setEndTimePointIsSet(boolean value) {
    if (!value) {
      this.endTimePoint = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case START_TIME_POINT:
      if (value == null) {
        unsetStartTimePoint();
      } else {
        setStartTimePoint((DayTimePoint)value);
      }
      break;

    case END_TIME_POINT:
      if (value == null) {
        unsetEndTimePoint();
      } else {
        setEndTimePoint((DayTimePoint)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case START_TIME_POINT:
      return getStartTimePoint();

    case END_TIME_POINT:
      return getEndTimePoint();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case START_TIME_POINT:
      return isSetStartTimePoint();
    case END_TIME_POINT:
      return isSetEndTimePoint();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DayTimeSubItem)
      return this.equals((DayTimeSubItem)that);
    return false;
  }

  public boolean equals(DayTimeSubItem that) {
    if (that == null)
      return false;

    boolean this_present_startTimePoint = true && this.isSetStartTimePoint();
    boolean that_present_startTimePoint = true && that.isSetStartTimePoint();
    if (this_present_startTimePoint || that_present_startTimePoint) {
      if (!(this_present_startTimePoint && that_present_startTimePoint))
        return false;
      if (!this.startTimePoint.equals(that.startTimePoint))
        return false;
    }

    boolean this_present_endTimePoint = true && this.isSetEndTimePoint();
    boolean that_present_endTimePoint = true && that.isSetEndTimePoint();
    if (this_present_endTimePoint || that_present_endTimePoint) {
      if (!(this_present_endTimePoint && that_present_endTimePoint))
        return false;
      if (!this.endTimePoint.equals(that.endTimePoint))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(DayTimeSubItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    DayTimeSubItem typedOther = (DayTimeSubItem)other;

    lastComparison = Boolean.valueOf(isSetStartTimePoint()).compareTo(typedOther.isSetStartTimePoint());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartTimePoint()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startTimePoint, typedOther.startTimePoint);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEndTimePoint()).compareTo(typedOther.isSetEndTimePoint());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndTimePoint()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endTimePoint, typedOther.endTimePoint);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DayTimeSubItem(");
    boolean first = true;

    if (isSetStartTimePoint()) {
      sb.append("startTimePoint:");
      if (this.startTimePoint == null) {
        sb.append("null");
      } else {
        sb.append(this.startTimePoint);
      }
      first = false;
    }
    if (isSetEndTimePoint()) {
      if (!first) sb.append(", ");
      sb.append("endTimePoint:");
      if (this.endTimePoint == null) {
        sb.append("null");
      } else {
        sb.append(this.endTimePoint);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (startTimePoint != null) {
      startTimePoint.validate();
    }
    if (endTimePoint != null) {
      endTimePoint.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DayTimeSubItemStandardSchemeFactory implements SchemeFactory {
    public DayTimeSubItemStandardScheme getScheme() {
      return new DayTimeSubItemStandardScheme();
    }
  }

  private static class DayTimeSubItemStandardScheme extends StandardScheme<DayTimeSubItem> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DayTimeSubItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // START_TIME_POINT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.startTimePoint = new DayTimePoint();
              struct.startTimePoint.read(iprot);
              struct.setStartTimePointIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // END_TIME_POINT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.endTimePoint = new DayTimePoint();
              struct.endTimePoint.read(iprot);
              struct.setEndTimePointIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DayTimeSubItem struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.startTimePoint != null) {
        if (struct.isSetStartTimePoint()) {
          oprot.writeFieldBegin(START_TIME_POINT_FIELD_DESC);
          struct.startTimePoint.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.endTimePoint != null) {
        if (struct.isSetEndTimePoint()) {
          oprot.writeFieldBegin(END_TIME_POINT_FIELD_DESC);
          struct.endTimePoint.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DayTimeSubItemTupleSchemeFactory implements SchemeFactory {
    public DayTimeSubItemTupleScheme getScheme() {
      return new DayTimeSubItemTupleScheme();
    }
  }

  private static class DayTimeSubItemTupleScheme extends TupleScheme<DayTimeSubItem> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DayTimeSubItem struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStartTimePoint()) {
        optionals.set(0);
      }
      if (struct.isSetEndTimePoint()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetStartTimePoint()) {
        struct.startTimePoint.write(oprot);
      }
      if (struct.isSetEndTimePoint()) {
        struct.endTimePoint.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DayTimeSubItem struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.startTimePoint = new DayTimePoint();
        struct.startTimePoint.read(iprot);
        struct.setStartTimePointIsSet(true);
      }
      if (incoming.get(1)) {
        struct.endTimePoint = new DayTimePoint();
        struct.endTimePoint.read(iprot);
        struct.setEndTimePointIsSet(true);
      }
    }
  }

}

