/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule.rule;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PenaltyChangeTypeEnum implements org.apache.thrift.TEnum {
  CHANGE(0),
  NOSHOW(1),
  REISSUE(2),
  REROUTE(3),
  ENDORSE(4),
  UPSELL(5);

  private final int value;

  private PenaltyChangeTypeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PenaltyChangeTypeEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return CHANGE;
      case 1:
        return NOSHOW;
      case 2:
        return REISSUE;
      case 3:
        return REROUTE;
      case 4:
        return ENDORSE;
      case 5:
        return UPSELL;
      default:
        return null;
    }
  }
}
