/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule.rule;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PenaltyTypeEnum implements org.apache.thrift.TEnum {
  NOT_PERMIT(0),
  PERMIT(1),
  RATIO(2),
  FEE(3),
  HIGHER(4);

  private final int value;

  private PenaltyTypeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PenaltyTypeEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return NOT_PERMIT;
      case 1:
        return PERMIT;
      case 2:
        return RATIO;
      case 3:
        return FEE;
      case 4:
        return HIGHER;
      default:
        return null;
    }
  }
}
