/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule.rule;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PenaltyAdditionEnum implements org.apache.thrift.TEnum {
  NO_CLASS_CHANGE(0),
  NO_AHEAD(1),
  NO_EXTENTION(2);

  private final int value;

  private PenaltyAdditionEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PenaltyAdditionEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return NO_CLASS_CHANGE;
      case 1:
        return NO_AHEAD;
      case 2:
        return NO_EXTENTION;
      default:
        return null;
    }
  }
}
