/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travelzen.farerule.rule;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TimeTypeEnum implements org.apache.thrift.TEnum {
  DAY(0),
  MONTH(1),
  YEAR(2),
  HOUR(3);

  private final int value;

  private TimeTypeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TimeTypeEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return DAY;
      case 1:
        return MONTH;
      case 2:
        return YEAR;
      case 3:
        return HOUR;
      default:
        return null;
    }
  }
}
